language: python
install:
  - pip install -r requirements.txt
deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  app: restapi
  domain: 256px
  on:
    repo: 256px/256px-backscrub
