language: node_js
node_js:
  - "0.11"
  - "0.10"
install:
  - npm install
deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  app: restapi
  domain: 256px
  on:
    repo: 256px/256px-backscrub
