language: node_js
node_js:
  - "0.11"
  - "0.10"
install:
  - npm install
deploy:
  provider: openshift
  on: "master"
  user: openshiftlogin
  password: openshiftpassword
  domain: "restapi-256px.rhcloud.com"
