language: node_js
node_js:
  - "0.11"
  - "0.10"
install:
  - npm install
deploy:
 provider: openshift
 user: $OPENSHIFT_USERNAME
 password: $OPENSHIFT_PASSWORD
 app: $OPENSHIFT_APP_NAME
 domain: $OPENSHIFT_APP_NAMESPACE
